(defun real-length (str)
  (do ((i 0 (1+ i))
       (count 0 (1+ count)))
      ((= i (length str)) (- count 2))
    (when (char= (char str i) #\\)
      (incf i (if (char= (char str (1+ i)) #\x) 3 1)))))

(defun adv08 (filename)
  (with-open-file (s filename)
    (loop for line = (read-line s nil)
          while line sum (- (length line) (real-length line)))))

(defun encoded-length (str)
  (do ((i 0 (1+ i))
       (count 0 (1+ count)))
      ((= i (length str)) (+ count 2))
    (when (or (char= (char str i) #\\)
              (char= (char str i) #\"))
      (incf count))))

(defun adv08b (filename)
  (with-open-file (s filename)
    (loop for line = (read-line s nil)
          while line sum (- (encoded-length line) (length line)))))
